// DO NOT EDIT THIS FILE

package {{.Name}}

import (
	"github.com/vasiliyl/playwand/proto"
)


{{define "message"}}

{{$exportedMessageStructName := Exported .Interface .Name .Kind}}


type {{$exportedMessageStructName}} struct {
	id proto.ObjectId
	{{range .Args}}
	{{Exported .Name}} {{GoType .Type}}
	{{end}}
}

func (m {{$exportedMessageStructName}}) opcode() uint16 { return {{.Opcode}} }

func (m *{{$exportedMessageStructName}}) readFrom(c *proto.Conn) (err error) {
	{{range .Args}}
	if err = c.ReadValue((*{{WlType .Type}})(&m.{{Exported .Name}})); err != nil {
		return
	}
	{{end}}
	return nil
}

func (m {{$exportedMessageStructName}}) WriteTo(c *proto.Conn) (err error) {
	vars := []proto.Type{ {{range .Args}}
	(*{{WlType .Type}})(&m.{{Exported .Name}}),
	{{end}} }
	return c.WriteValues(m.id, m.opcode(), vars...)
}
{{end}}

{{range .Interfaces}} 


{{range .Requests}}
{{template "message" .}}
{{end}}
{{range .Events}}
{{template "message" .}}
{{end}}

{{end}}

